"""Core domain enums defining system states, roles, and operation types."""

from enum import Enum


class PrincipalRole(str, Enum):
    ADMIN = "ADMIN"
    DEVELOPER = "DEVELOPER"
    AUDITOR = "AUDITOR"
    SERVICE = "SERVICE"


class AgentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"


class MandateStatus(str, Enum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    EXHAUSTED = "EXHAUSTED"
    REVOKED = "REVOKED"


class OperationType(str, Enum):
    CREATE_ORDER = "CREATE_ORDER"
    CAPTURE_PAYMENT = "CAPTURE_PAYMENT"
    CREATE_REFUND = "CREATE_REFUND"
    CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"
    CANCEL_PAYMENT_LINK = "CANCEL_PAYMENT_LINK"


class OperationStatus(str, Enum):
    INITIATED = "INITIATED"
    POLICY_CHECK_PENDING = "POLICY_CHECK_PENDING"
    POLICY_APPROVED = "POLICY_APPROVED"
    POLICY_REJECTED = "POLICY_REJECTED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class TransactionStatus(str, Enum):
    CREATED = "CREATED"
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    REFUNDED = "REFUNDED"
    FAILED = "FAILED"


class AuditAction(str, Enum):
    PRINCIPAL_CREATED = "PRINCIPAL_CREATED"
    AGENT_REGISTERED = "AGENT_REGISTERED"
    AGENT_STATUS_CHANGED = "AGENT_STATUS_CHANGED"
    MANDATE_ISSUED = "MANDATE_ISSUED"
    MANDATE_REVOKED = "MANDATE_REVOKED"
    OPERATION_REQUESTED = "OPERATION_REQUESTED"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    OPERATION_EXECUTED = "OPERATION_EXECUTED"
    TRANSACTION_RECORDED = "TRANSACTION_RECORDED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
